### ISSUE TITLE
Host a local server with this implementation?

### ISSUE THREAD

**Issue by supagu** [vasild/cpp-ipfs-http-client#23]
Hi,

I just got this library up and running only to realise that it seems to connect to an existing local node. I was expecting it to host a local node also. 
Am I correct in this? Do I need to host my own local server then use this library to connect to my local server?

It would be helpful to update the documentation with this information.

**Comment by vasild** [comment]
Yes, this library needs to connect to a running IPFS node. As the library connects to the node via TCP it is not necessary that the node runs locally. I reworded a bit the README to make this more clear, hopefully.

Thanks for the feedback!
