### ISSUE TITLE
Use infura with cpp-ipfs

### ISSUE THREAD

**Issue by tiphainehenry** [vasild/cpp-ipfs-http-client#52]
Hi, 

I am trying to use cpp-ipfs-http-client with Infura. The code works fine with a local ipfs daemon (ipfs::Client client("localhost", 5001), but the port seems closed when using Infura. Here are the diferent configurations I tried: 
`ipfs::Client client("https://ipfs.infura.io", 5001);
ipfs::Client client("ipfs.infura.io", 5001); 
ipfs::Client client("ipfs.infura.io", 5001, "https");
`
The terminal issues connection failed errors.
By any chance, did you try using Infura or similar tools smoothly with cpp-ipfs-http-client? 

Thanks for your help !

**Comment by danger89** [comment]
Hi!

I'm not that familiar with infura.io to be honest. But my first guess is that you need to authenticate yourself.

Infura expects basic authentication via "PROJECT_ID:PROJECT_SECRET" (Project id is your username, and the secret is the password basically. 

For that to work. We need to extent the [existing code](https://github.com/vasild/cpp-ipfs-http-client/blob/master/src/http/transport-curl.cc) with `curl_easy_setopt(_curl, CURLOPT_USERPWD, char *userpwd)`. Allowing you to set and pass the username/password to the HTTP requests.

**Comment by tiphainehenry** [comment]
Hi, thank you for your input, 
After some inquiry, there is finally no need to extend the code for Infura authentification, the following command works fine: `ipfs::Client client("ipfs.infura.io", 5001, "20s", "https://");`

**Comment by danger89** [comment]
Ah great! Ow I get it again. It was the hostname that doesn't expect the protocol but only the host of the domain.
