### ISSUE TITLE
#include <nlohmann/adl_serializer.hpp> not installed

### ISSUE THREAD

**Issue by Lecrapouille** [vasild/cpp-ipfs-http-client#64]
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib/libipfs-http-client.a
-- Installing: /usr/local/include/ipfs/client.h
-- Installing: /usr/local/include/ipfs/http/transport.h
-- Installing: /usr/local/include/nlohmann/json.hpp

But nlohmann/adl_serializer.hpp is not copied while present in ./build/_deps/json-src/include/nlohmann/adl_serializer.hpp

Therefore this exemple https://github.com/vasild/cpp-ipfs-http-client#usage does not compile:
#include <nlohmann/adl_serializer.hpp> not found

Same for the whole folder.
Edit: -I ./build/_deps/json-src/include/ fixing my compilation issue but this line:
```
install(FILES ${json_SOURCE_DIR}/include/nlohmann/json.hpp DESTINATION include/nlohmann)
```
should be fixed

**Comment by melroy89** [comment]
Same should fetch the JSON package, as you can see here: https://github.com/vasild/cpp-ipfs-http-client/blob/master/CMakeLists.txt#LL62C1-L62C21

Be sure your CMake version is up to date..
